- name: Install nginx
  apt:
    name: nginx
    state: present
    update-cache: true
  when: ansible_os_family == "Debian"
  notify: Nginx Systemd

- name: Replace config file
  vars:
    nginx_user: user
    worker_processes: 2
    worker_connections: 256
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  register: result
  failed_when: result.failed == true
  notify: Reload Nginx
  
- name: Generate dynamic HTML from template
  template: src=templates/index.html.j2 dest={{ html_dir }} owner=root mode=0644
  notify: Reload Nginx
